#!/bin/bash
set -e

sample_size=$1
if [ -z ${sample_size} ]; then
	echo "usage: $0 <sample size>" >&2
	exit 1
fi

wine ampl JointMDPNonlinearEqn.run
matlab -nojvm -r "runMCJoint(${sample_size}); exit;" | tee DATA/jointMC.log
wine ampl JointMLEMathProgEC.run
